#
# Docker container for building openpaas-esn package
#
# Build:
# docker build -t linagora/esn-sabre .
#
# Run:
# docker run -d -p 8001:80 -e "SABRE_MONGO_HOST=192.168.0.1" -e "ESN_MONGO_HOST=192.168.0.1" linagora/esn-sabre
#

FROM debian:jessie
MAINTAINER Linagora Folks <openpaas@linagora.com>

# Install Packages
RUN apt-get update && \
#    DEBIAN_FRONTEND=noninteractive apt-get -y upgrade && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install apt-utils && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install git php5-curl php-pear php5-dev php5-fpm make && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install ruby-dev ruby build-essential && gem install fpm
RUN pecl install mongo

RUN curl -sS https://getcomposer.org/installer | php &&  mv composer.phar /usr/local/bin/composer.phar && ln -s /usr/local/bin/composer.phar /usr/local/bin/composer

# Configure PHP
RUN echo "extension=mongo.so" >> /etc/php5/fpm/php.ini && \
    echo "extension=mongo.so" >> /etc/php5/cli/php.ini

# Set up Sabre DAV
WORKDIR /var/www/html/openpaas-dav
COPY . /var/www/html/openpaas-dav

RUN composer update --no-dev

RUN mv esn.php index.php

RUN mkdir -p /tmp && cp -a ../openpaas-dav /tmp && mkdir -p debian/package/var/www/html && mv /tmp/openpaas-dav debian/package/var/www/html && rm -rf debian/package/var/www/html/openpaas-dav/debian
WORKDIR /var/www/html/openpaas-dav/debian
RUN fpm -s dir -t deb \
  -n openpaas-dav \
  -v 1.0.0 \
  --iteration 1 \
  -a x86_64 \
  -d nginx \
  -d php5-fpm \
  -C package \
  --after-install openpaas-dav.postinst \
  .
