#
# Docker container for ESN Sabre frontend development.
#
# Build:
# docker build -t linagora/esn-sabre-dev .
#

FROM linagora/esn-sabre
LABEL maintainer Linagora Folks <openpaas@linagora.com>

RUN pecl install xdebug

CMD ["sh", "./scripts/start.sh"]
