FROM php:7.0.31-cli-stretch

MAINTAINER Linagora Folks <lgs-openpaas-dev@linagora.com>

RUN apt-get update && \
    apt-get -y install unzip git && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN docker-php-ext-install bcmath
RUN pecl install mongodb
RUN docker-php-ext-enable mongodb
RUN curl https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer.phar
RUN ln -s /usr/local/bin/composer.phar /usr/local/bin/composer
